# -*- coding: utf-8 -*-
"""Movie Recommender System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pyVtR1s83YBi0Wl4RPYf46Skr14ztZO
"""

import numpy as np
import pandas as pd

movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

movies.head(1)

credits.head(1)

credits.head(1)['cast'].values

#merge two dataframes
movies = movies.merge(credits,on='title')

movies.head(1)

movies.info()

#Important Columns
#genres
#id
#keywords
#title
#overview
#release date
#revenue
#cast
#crew
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

movies.info()

#Main Data
movies.head()

movies.dropna(inplace=True)

movies.isnull().sum()

movies.duplicated().sum()

movies.iloc[0].genres

#[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]
#['Action','Adventure','Fantasy','Science Fiction']

def convert(obj):
  L = []
  for i in obj:
    L.append(i['name'])
  return L

import ast
movies['genres'] = movies['genres'].apply(ast.literal_eval)
movies['genres'] = movies['genres'].apply(convert)

movies.head()

movies.iloc[0].keywords

#[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]
#['culture clash','future','space war','space colony','society','space travel','futuristic','romance','space','alien','tribe','alien planet','cgi','marine','soldier','battle','love affair','anti war','power relations','mind and soul','3d'}]

def convert(obj):
  L = []
  for i in obj:
    L.append(i['name'])
  return L
convert([{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}])

import ast
movies['keywords'] = movies['keywords'].apply(ast.literal_eval)
movies['keywords'] = movies['keywords'].apply(convert)

movies.head()

movies.iloc[0].cast

def convert(obj):
  L = []
  counter = 0
  for i in obj:
    if counter != 3:
      L.append(i['name'])
      counter+=1
    else:
      break
  return L

import ast
movies['cast'] = movies['cast'].apply(ast.literal_eval)
movies['cast'] = movies['cast'].apply(convert)

movies.head()

movies.iloc[0].crew

def fetch_director(obj):
  L = []
  for i in ast.literal_eval(obj):
      if i['job'] == 'Director':
          L.append(i['name'])
          break
  return L

movies['crew']=movies['crew'].apply(fetch_director)

movies.head()

movies['overview'][0]

#to reduce space between words
movies['overview'] = movies['overview'].apply(lambda x:x.split())

movies.head()

movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])

movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

movies.head()

#Concatenate all lists
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

movies.head()

new_df = movies[['movie_id','title','tags']]

#to convert tags list into string
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

new_df.head()

new_df['tags'][0]

#to convert uppercase into lowercase
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

new_df.head()

!pip install nltk

import nltk

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
  y = []
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron')

new_df['tags'] = new_df['tags'].apply(stem)

new_df['tags'][0]

new_df['tags'][1]

#for count vectorization
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

vectors = cv.fit_transform(new_df['tags']).toarray()

vectors

vectors[0]

cv.get_feature_names_out()

from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

similarity

#similarity of first movie with other movies
similarity[0]

def recommend(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
  for i in movies_list:
      print(new_df.iloc[i[0]].title)

recommend('Avatar')

recommend('Batman Begins')

recommend('Iron Man')

import pickle

pickle.dump(new_df,open('movies.pkl','wb'))

new_df